extern "C" double Vrtx_P0d0_plus(size_t n, double q)
  {
    return ...
  }
    extern "C" double Vrtx_P0d0_minus(size_t n, double q)
    ...
    ...

    extern "C" double Vrtx_P0d545_plus(size_t n, double q)
    ...
    extern "C" double Vrtx_P0d545_minus(size_t n, double q)
    ...
    extern "C" double Vrtx_P17d44_plus(size_t n, double q)
    ...
    extern "C" double Vrtx_P17d44_minus(size_t n, double q)
    ...